### ISSUE TITLE
Breadcrumbs spacing

### ISSUE THREAD

**Issue by Herm71** [ucsc/site-specialevents#203]
This might be a bit trivial, but the `/` separator in the breadcrumbs has one `&nbsp` on the left but two on the right.
![screenshot from 2020-04-06 10-33-29](https://user-images.githubusercontent.com/1000543/78588030-bfb01380-77f2-11ea-8c16-1e786aed83d5.png)

**Comment by luckyluke007** [comment]
Fixed
